# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    env:
      NODE_ENV: test
      TEST_DB_CLIENT: pg
      TEST_DB_HOST: localhost
      TEST_DB_NAME: product_gellary_test
      TEST_DB_USER: db_user
      TEST_DB_PASSWORD: db_password
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: product_gellary_test
          POSTGRES_PASSWORD: db_user
          POSTGRES_USER: db_password
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install packages
        run: |
          npm i -g knex
          npm i -g eslint
          npm i -g typescript
          npm install
          tsc
      - name: DB config
        run: npm run reset
      - name: Run linter
        run: npm run lint
      - name: run tests
        run: npm test
